### PR TITLE
.github/workflows/ci-sage.yml: Update to Docker push logic

### PR DESCRIPTION
**Pull request by mkoeppe**
We update the Docker push logic:
- use what is implemented in tox.ini
- prefix the package name with 'cysignals-' to avoid clashes with the packages pushed by Sage CI workflows
-  use `latest` or `dev` Docker tags for release tags

### CODE REVIEW

**Comment by kliem** [comment]
It seems that the CI-workflow is currently broken, see tests #166.

     ./bootstrap: 161: ./bootstrap: ./bootstrap-conda: not found
    Bootstrap failed. Either install autotools and gettext; or run bootstrap with
    the -d option to download the auto-generated files instead.

In general, I hardly understand what is going on in this workflow anymore.

**Comment by mkoeppe** [comment]
This is fixed in https://trac.sagemath.org/ticket/33926

**Comment by kliem** [comment]
I see, so no need to update here. Great.

**Comment by mkoeppe** [comment]
I have merged [#33926](https://trac.sagemath.org/ticket/33926) into the ticket branch of the "CI target ticket for cysignals" [#32579](https://trac.sagemath.org/ticket/32579). So it will now be used by the workflow.

**Comment by mkoeppe** [comment]
Outdated

**Pull request closed without merging**
