### PR TITLE
README.rst, VERSION: Update to 1.11.3

### PR DESCRIPTION
**Pull request by mkoeppe**
After merging this PR, a release can be tagged. @dimpase @malb

### CODE REVIEW

**Comment by dimpase** [comment]
one problem  to fix for the release is to make docs build properly.

**Comment by dimpase** [comment]
can we apply #187 first?

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by dimpase** [comment]
Do you know how to make releases here?

**Comment by mkoeppe** [comment]
Just create a release tag. If all works well, it will push sdist and wheel to PyPI. (It should have the necessary credentials from the sagemath org...)

**Comment by dimpase** [comment]
there was already the source release on PyPI, not sure why :-)

**Comment by dimpase** [comment]
Should I open a PR to bump cysignals in Sage?

**Comment by dimpase** [comment]
https://github.com/sagemath/sage/pull/36402

**Pull request merged**
