### PR TITLE
Add pyproject.toml, remove Cython from setup_requires, install_requires

### LINKED ISSUE #171: Remove Cython from install-requires
It is only a build dep; it should be declared in pyproject.toml

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #171.

For now, we use "Cython < 3". 
Fixes for Cython 3 in separate PRs.

### CODE REVIEW

**Comment by mkoeppe** [comment]
@dimpase This fixes the wheel build. Please review & merge -- as a first step.

**Comment by malb** [comment]
From the GitHub Actions it seems the change doesn't take, they still use Cython 3.0?

**Comment by dimpase** [comment]
GH actions are just badly broken here

**Comment by malb** [comment]
LGTM, if we ignore GH I think we can merge this one

**Comment by dimpase** [comment]
let me test how it plays with Sage

**Comment by dimpase** [comment]
OK!

**Review by dimpase — COMMENTED** [review]
lgtm

**Pull request merged**
