### PR TITLE
Cygwin builds on AppVeyor

### PR DESCRIPTION
**Pull request by embray**
Implements #92 in a manner intended to be compatible with #76.  Depends on #94.

It would probably be best to implement #76 first and then merge this into its `.appveyor.yml`.  But we could also do it the other way around depending on how things go with #76.

See https://ci.appveyor.com/project/embray/cysignals for sample builds.

### CODE REVIEW

**Comment by embray** [comment]
Went ahead and hooked up AppVeyor to this repository.  You can see the successful build of this PR below.

**Comment by embray** [comment]
> What's `os.name` on Cygwin?
`'posix'`

**Comment by jdemeyer** [comment]
Psychologically, I find it easier to list the conditions for running a doctest in the positive sense: I prefer "run this test only if X" instead of "skip this test if not X". In SageMath, it also works like that: we say `# optional - PKG` for "run this test only if PKG is available`.

So I would prefer flags like `OPTIONAL_POSIX` or `POSIX_ONLY`.

**Comment by embray** [comment]
Ok but this would make more sense to discuss on #94.  Sorry, I should have clarified that this PR is based on that one.

**Pull request closed without merging**
