### PR TITLE
Cysignals for windows

### PR DESCRIPTION
**Pull request by jdemeyer**
Modify cysignals for windows compatibility

### CODE REVIEW

**Comment by embray** [comment]
I saw an old comment you left mentioning trouble testing in Python 3.  Is that still being a problem?  For Cygwin I want to add testing for at least 3.6 and maybe 3.7 now that there's a 3.7 package for Cygwin.  I don't think there was any specific reason I left it off for now, except maybe just to reduce the problem space.

**Comment by jdemeyer** [comment]
> I saw an old comment you left mentioning trouble testing in Python 3. Is that still being a problem?

No, as far as I know, there are no problems with Python 3. The remaining problems are all related to the fact that signal handling on Windows is a very thing from POSIX :-)

There are still some tests to be fixed before this is ready to merge.

**Comment by jdemeyer** [comment]
I just realized that "a different thread from the main thread receives a signal" is something that I'll need to fix anyway for #109. So I'll probably generalize the `sig_mapped_to_FPE` thing.

**Comment by tobiasdiez** [comment]
What's the status of this PR? Windows support would be very welcome and would probably fix https://github.com/sagemath/cysignals/issues/119 as well.

**Comment by kliem** [comment]
Maybe it would also be a good step for windows, to get rid of `configure.ac`?

**Pull request closed without merging**
