### PR TITLE
[WIP] Run CI using Conda

### PR DESCRIPTION
**Pull request by jdemeyer**

### CODE REVIEW

**Comment by jdemeyer** [comment]
CC @saraedum

**Comment by jdemeyer** [comment]
What's up with conda-forge and Python 3.4? Has support for that version been dropped?

**Comment by saraedum** [comment]
Looks very reasonable. Can travis run tests on Linux & OSX?

**Comment by jdemeyer** [comment]
> Can travis run tests on Linux & OSX?

Yes, Linux and OS X, both x86_64.

**Comment by jdemeyer** [comment]
@isuruf: I am trying again to get this working. Unfortuntaly, PARI doesn't work: do I need to do anything special to link against `-lpari` within Conda?

**Comment by isuruf** [comment]
@jdemeyer, you'll have to set `LDFLAGS="-L$PREFIX/lib -Wl,-rpath,$PREFIX/lib` and `CPPFLAGS=-I$PREFIX/include`

**Comment by jdemeyer** [comment]
OK, I was assuming that Conda would set something like that automatically.

**Comment by isuruf** [comment]
Should have been $CONDA_PREFIX instead of $PREFIX.

**Comment by jdemeyer** [comment]
Thanks! This seems to be working now.

**Comment by jdemeyer** [comment]
Thanks @isuruf !

**Pull request merged**
