### PR TITLE
Cygwin builds on AppVeyor

### PR DESCRIPTION
**Pull request by jdemeyer**
CC @embray 

Unfortunately failing with
```
gcc -fno-strict-aliasing -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python2/python2-2.7.14-1.x86_64/build=/usr/src/debug/python2-2.7.14-1 -fdebug-prefix-map=/usr/src/ports/python2/python2-2.7.14-1.x86_64/src/Python-2.7.14=/usr/src/debug/python2-2.7.14-1 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/cygdrive/c/projects/cysignals/tmp/site-packages/cysignals -I/usr/include/python2.7 -c cysignals_example.cpp -o build/temp.cygwin-2.10.0-x86_64-2.7/cysignals_example.o
gcc: error: spawn: No such file or directory
```

This may be relevant: https://stackoverflow.com/questions/16621529/gcc-fails-with-spawn-no-such-file-or-directory

### CODE REVIEW

**Comment by embray** [comment]
Is the C++ example file new?  Might just be missing the right g++ package...

**Comment by jdemeyer** [comment]
> Is the C++ example file new?

The example is not new, but the fact that it is C++ (as opposed to C) might be new.

**Comment by jdemeyer** [comment]
Minor question: what does this mean in `.appveyor.yml`:
```
version: 1.0.{build}
```
That's confusing because now I see for example "cysignals 1.0.11" in the AppVeyor page.

**Comment by jdemeyer** [comment]
@embray, you should have write access to this github repo, you can just amend your commits.

**Comment by embray** [comment]
It's basically boilerplate
https://www.appveyor.com/docs/build-configuration/#build-versioning

It's not the version of the software but a "build version". I think how we use it is kind of up to us, and I can just as easily do away with the `1.0` part and just use:

`version: {build}`.

**Comment by jdemeyer** [comment]
Is there any particular reason that you are testing only Python 2.7 and not some Python 3.x?

**Comment by jdemeyer** [comment]
I am asking because we're having some problems on #76 with silly errors from AppVeyor like
```
export PYTHONPATH="`pwd`/tmp/site-packages" && cd example && python setup.py clean build
/usr/bin/sh: python: command not found
```

**Pull request merged**
