### PR TITLE
Update build system to use Meson

### PR DESCRIPTION
**Pull request by tobiasdiez**
Following the example of Scipy/Numpy and https://github.com/sagemath/sage/pull/36524, the build system is migrated to Meson.

I tried to stay as close as possible to the original autoconf implementation. A few differences are:
- No longer need to auto-generate `signals.pxd`, but have it at as a normal source file.
- Changed the authors to `Sage Developers` to align with the main sage repo. I'm unsure about this one and happy to revert it.
- Drop Python < 3.9 in alignment with https://scientific-python.org/specs/spec-0000/
- Remove the special handling when `MINSIGSTKSZ_IS_CONSTANT` (I had trouble making it compile and it's not constant for recent versions of glibc anyway)
- Remove the "ci-with-sage" jobs in the github action, which are non-working on the main branch and I've also no idea how to make them compatible with meson; I also think the current ci runs should give a pretty good coverage.
- Include the code of `implementation_cygwin.c` directly in `implementation.c` since I was not able to make it compile (it's also a bit hard for me to work on the cygwin code since I only have the ci to test it.)

Closes https://github.com/sagemath/cysignals/issues/179 (obsolete now)

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Tests are green, so this is also ready to go.

Please squash after https://github.com/sagemath/cysignals/pull/209.

**Comment by dimpase** [comment]
something happened during a rebase? There are no `meson.build` files anywhere

**Review by dimpase — CHANGES_REQUESTED** [review]
please check that the rebase went OK (it seems it hasn't)

**Comment by tobiasdiez** [comment]
Right, thanks. Something went wrong with merging https://github.com/sagemath/cysignals/pull/209 into this branch here. I've kinda fixed it locally, but it would be easier if https://github.com/sagemath/cysignals/pull/209 can be merged first (and squashed!) into main.

**Comment by tobiasdiez** [comment]
Uff, tests are finally green.

**Comment by fchapoton** [comment]
Would you agree to engage yourself to maintain this for the years to come ?

**Comment by dimpase** [comment]
meson is a widely used and documented, unlike our present system to build sagelib.

**Comment by fchapoton** [comment]
So we both agree that it's a good idea to merge, right ?

**Comment by tobiasdiez** [comment]
> Would you agree to engage yourself to maintain this for the years to come ?

That's hard to promise but yes I'm willing to (help) maintaining it. The meson build info is also pretty straightforward, so it shouldn't be too hard for someone else to modify it.

Please merge #209 before this one here, and squash this PR to have a cleaner git history. Thanks!

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by tobiasdiez** [comment]
Thanks @dimpase and @fchapoton!

**Pull request merged**
