### PR TITLE
Build machinery hardening

### PR DESCRIPTION
**Pull request by jgmbenoit**
These 3 patches slightly improve the building machinery.
Having said that, it would be a good idea to have checks that does not involve a system wide installation.

### CODE REVIEW

**Comment by jdemeyer** [comment]
I think it's better to separate the various issues into independent pull requests for easier discussion.

**Comment by jgmbenoit** [comment]
Somehow I am agree, it is why I furnish three patches. Anyway, I guess I have to update them for version 1.2 .

**Comment by jdemeyer** [comment]
> Somehow I am agree, it is why I furnish three patches.

Right, but with 3 pull requests (instead of 1) it is easier to discuss or merge individual patches.

**Comment by jgmbenoit** [comment]
Ok, I will keep it in mind.

**Comment by jdemeyer** [comment]
I'm going to close this for now. If you want to continue the discussion, please open 1 pull request for each issue.

**Pull request closed without merging**
