### PR TITLE
Remove appveyor

### PR DESCRIPTION
**Pull request by tobiasdiez**
It fails installing cygwin and we have github actions now anyway.

### CODE REVIEW

**Comment by dimpase** [comment]
could you rebase this?

**Review by dimpase — APPROVED** [review]
LGTM otherwise

**Comment by fchapoton** [comment]
sorry for the inconvience : I tried and failed to fix the appveyor configuration

**Review by tobiasdiez — COMMENTED** [review]
> sorry for the inconvience : I tried and failed to fix the appveyor configuration 

No problem! Since there is now also a github action for cygwin, I think the appveyor workflow can be safely removed.

**Pull request merged**
